name: Build Flutter for Windows

on:
  push:
    branches: [issue/#89/app-crash]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Flutter App on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  

      - name: Set up Flutter (beta channel)
        uses: subosito/flutter-action@v2
        with:
          channel: beta  

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows executable
        run: flutter build windows

      - name: List files in build/windows/x64/runner/Release
        run: dir build/windows/x64/runner/Release/

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4  
        with:
          name: flutter-windows-build
          path: build/windows/x64/runner/Release/ubiqus_app.exe  # Ruta correcta para el artefacto
